### ISSUE TITLE
Prevent creating a new document with the same name as an existing document

### ISSUE THREAD

**Issue by neilparikh** [thesephist/merlot#5]
Right now, if you create another document with the same name as an existing document, the content from the existing document is lost.

**Comment by thesephist** [comment]
I'm going to handle this by only allowing creating documents with new names. If you type in a name that already exists, the dialog box should say something along the lines of "You already have a file named X."

**Comment by thesephist** [comment]
[Just patched up the "Add a file" dialog](https://github.com/thesephist/merlot/commit/54be1fecac4bb414a6354946b2a83de04ab3cd2e) so that it won't let you create files with duplicate names anymore. Sorry if this caused you any trouble, and thanks for pointing it out!

![Screen Shot 2022-02-06 at 04 21 10](https://user-images.githubusercontent.com/5403917/152674865-eddfc107-c19d-4750-b53f-043ab3958c37.png)

**Comment by neilparikh** [comment]
No worries, I only encountered it once and I had a backup of the deleted document, so no problems caused.

Thanks for the fix (and for creating Merlot)!
